apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:    
  - deployment.yml
  - service.yml
  - ingress.yml
configMapGenerator:    
  - name: gateway-config 
    files:                
      - application.yml 
    options: 
      labels:     
        app: gateway-service